Mnist Viewer: MainWindow Class Reference
MainWindow Class Reference
The MainWindow class is used to hold the GUI elements of the project.
#include <mainwindow.h>
Public Slots
void displayExample (int index, const QImage &image, int label, int prediction)
Receive an image, its actual label, and its predicted label for publishing to the screen.
void trainingUpdate (unsigned int batch, unsigned int total_batches, unsigned int epoch, unsigned int total_epochs, float latest_loss)
Called when an update has been received by the training network.
Signals
void iterateImage (int difference)
Signal the connected Network object to change the example displayed.
void startTraining (unsigned int batch_size, unsigned int epochs)
Signals the connected Network object to train the network.
Public Member Functions
MainWindow (QWidget *parent=nullptr)
The default constructor.
~MainWindow ()
Private Member Functions
void nextButtonClicked (bool checked)
Called when the next button emits a clicked event.
void previousButtonClicked (bool checked)
Called when the previous button emits a clicked event.
void trainButtonClicked (bool checked)
Called when the training button emits a clicked event.
Private Attributes
QScopedPointer< TrainingProgress > training_window
The pointer to hold the secondary gui to display training progress.
Ui::MainWindow * ui
The pointer to the GUI elements generated from the mainwindow.ui file.
Friends
class TestMainWindow
TestMainWindow is a friend class so that it can properly test ui elements of this class.
Detailed Description
The MainWindow class is used to hold the GUI elements of the project.
It displays the image, prediction, and label values. It also allows the user to scroll through images and begin training.
Definition at line 25 of file mainwindow.h.
Constructor & Destructor Documentation
MainWindow()
MainWindow::MainWindow (QWidget * parent = nullptr)
The default constructor.
Parameters
parent The QWidget that owns this object.
Definition at line 5 of file mainwindow.cpp.
                                        :
         QMainWindow(parent), ui(new Ui::MainWindow) {
     ui->setupUi(this);
     connect(ui->next_button, &QPushButton::clicked, this, &MainWindow::nextButtonClicked);
     connect(ui->previous_button, &QPushButton::clicked, this, &MainWindow::previousButtonClicked);
     connect(ui->train_button, &QPushButton::clicked, this, &MainWindow::trainButtonClicked);
     ui->truth_label->setText("");
     ui->prediction_label->setText("");
 }
References nextButtonClicked(), previousButtonClicked(), trainButtonClicked(), and ui.
~MainWindow()
MainWindow::~MainWindow ()
Definition at line 15 of file mainwindow.cpp.
{
     delete ui;
 }
References ui.
Member Function Documentation
displayExample
void MainWindow::displayExample (int index, const QImage & image, int label, int prediction) slot
Receive an image, its actual label, and its predicted label for publishing to the screen.
This slot will put the values in the right spots on the GUI when new images are received.
Parameters
index The index value associated with the example.
image The actual image to display. It is assumed to be a 28x28 8-bit grayscale.
label The real label for the image.
prediction The network predicted label.
Definition at line 19 of file mainwindow.cpp.
{
     ui->index_label->setText(QString("Image #") + QString::number(index));
     ui->image_label->setPixmap(QPixmap::fromImage(image.scaledToHeight(800), Qt::ImageConversionFlag::NoFormatConversion));
     ui->truth_label->setText(QString::number(label));
     ui->prediction_label->setText(QString::number(prediction));
     Q_UNUSED(index);
 }
References ui.
Referenced by main(), and TestMainWindow::updateImage().
iterateImage
void MainWindow::iterateImage (int difference) signal
Signal the connected Network object to change the example displayed.
It will advance or retreat the amount specified in difference. This could be any integer, but in practice is either -1, 0, or 1.
Parameters
difference The amount to increment the displayed image by.
Referenced by main(), nextButtonClicked(), and previousButtonClicked().
nextButtonClicked()
void MainWindow::nextButtonClicked (bool checked) private
Called when the next button emits a clicked event.
This method will emit a iterateImage signal with a value of 1.
Parameters
checked Unused If the button is depressed or not.
Definition at line 39 of file mainwindow.cpp.
{
     emit iterateImage(1);
     Q_UNUSED(checked);
 }
References iterateImage().
Referenced by MainWindow().
previousButtonClicked()
void MainWindow::previousButtonClicked (bool checked) private
Called when the previous button emits a clicked event.
This method will emit a iterateImage signal with a value of -1.
Parameters
checked Unused If the button is deperessed or not.
Definition at line 44 of file mainwindow.cpp.
{
     emit iterateImage(-1);
     Q_UNUSED(checked);
 }
References iterateImage().
Referenced by MainWindow().
startTraining
void MainWindow::startTraining (unsigned int batch_size, unsigned int epochs) signal
Signals the connected Network object to train the network.
Parameters
batch_size The number of examples in each batch.
epochs The number of iterations to train on.
Referenced by main(), and trainButtonClicked().
trainButtonClicked()
void MainWindow::trainButtonClicked (bool checked) private
Called when the training button emits a clicked event.
This method will emit a startTraining signal. Currently, it will only request a batch size of one with an epoch of one.
Parameters
checked Unused If the button is depressed or not.
Definition at line 49 of file mainwindow.cpp.
{
     emit startTraining(64, 1);
 }
References startTraining().
Referenced by MainWindow().
trainingUpdate
void MainWindow::trainingUpdate (unsigned int batch, unsigned int total_batches, unsigned int epoch, unsigned int total_epochs, float latest_loss) slot
Called when an update has been received by the training network.
This will update or create the progress bar GUI with the latest info. When it is shown that the training is complete (batch == total_batches && epoch == total_epochs), the window will close.
Parameters
batch The current batch number within this epoch.
total_batches The total batches for a given epoch.
epoch The current epoch.
total_epochs The total epochs for which this will run.
latest_loss The latest loss value from the network.
Definition at line 27 of file mainwindow.cpp.
{
     if (training_window.isNull()) {
         training_window.reset(new TrainingProgress(total_batches, total_epochs, this));
         training_window->show();
     }
     training_window->update(batch, epoch, latest_loss);
     if (batch == total_batches && epoch == total_epochs) {
         training_window->hide();
         training_window->deleteLater();
     }
 }
References training_window.
Referenced by main().
Friends And Related Function Documentation
TestMainWindow
friend class TestMainWindow friend
TestMainWindow is a friend class so that it can properly test ui elements of this class.
Definition at line 31 of file mainwindow.h.
Member Data Documentation
training_window
QScopedPointer<TrainingProgress> MainWindow::training_window private
The pointer to hold the secondary gui to display training progress.
Definition at line 96 of file mainwindow.h.
Referenced by trainingUpdate().
ui
Ui::MainWindow* MainWindow::ui private
The pointer to the GUI elements generated from the mainwindow.ui file.
Definition at line 100 of file mainwindow.h.
Referenced by TestMainWindow::callTraining(), TestMainWindow::cycleBackward(), TestMainWindow::cycleForward(), displayExample(), MainWindow(), TestMainWindow::updateImage(), and ~MainWindow().
The documentation for this class was generated from the following files:
include/mainwindow.h
src/mainwindow.cpp