Mnist Viewer: Network Class Reference
Network Class Reference
The backend class that handles data flow into and out of the network.
#include <network.h>
Public Slots
void changeImage (int increment)
The slot that records when a new image should be predicted and displayed.
void startTraining (unsigned int batch_size, unsigned int epochs)
The slot that requests to train the network on training data.
Signals
void example (int index, QImage image, int truth, int prediction)
A signal containing a new example and associated labels.
void trainingUpdate (unsigned int batch, unsigned int total_batches, unsigned int epoch, unsigned int total_epochs, float latest_loss)
A signal that periodically emits to showcase training progress.
Public Member Functions
Network (QObject *parent=nullptr)
The default constructor.
Private Member Functions
QImage convertToImage (torch::Tensor tensor)
Takes a Tensor and converts it into a QImage.
void sendImage ()
The method to predict the image and output a example signal.
Private Attributes
size_t current_index
The index of the current image that should be displayed.
QScopedPointer< torch::data::datasets::MNIST > data
A pointer to the loaded dataset.
const QString DATA_PATH = "C:/Users/kylem/Documents/dev/src/mnist-viewer/data"
The hard coded location of the dataset file.
torch::nn::Sequential network
The MNIST network that does the prediction.
Detailed Description
The backend class that handles data flow into and out of the network.
This class not only defines the network. It also sets up the slots and signals to receive and send out data to it. It will perform all the right type conversions to extract images, labels, and predictions from the example set.
In particular, the network has the following shape:
Layer Type Details
2D Convolution 32 3x3 Filters
ReLU Activation None
2D Max Pool 2x2 Filter
2D Convolution 2 3x3 Filters
ReLU Activation None
2D Max Pool 2x2 Filter
2D Convolution 1 3x3 Filter
ReLU Activation None
Flatten None
Full Layer 576 x 64
ReLU Activation None
Full Layer 64 x 10
Softmax Activation None
Definition at line 42 of file network.h.
Constructor & Destructor Documentation
Network()
Network::Network (QObject * parent = nullptr) explicit
The default constructor.
Parameters
parent A parent QObject class, as is usual for any class that inherits it.
Definition at line 5 of file network.cpp.
                                  :
         QObject(parent),
         network(
                 torch::nn::Conv2d(torch::nn::Conv2dOptions(1, 32, 3)),
                 torch::nn::ReLU(torch::nn::ReLUOptions()),
                 torch::nn::MaxPool2d(torch::nn::MaxPool2dOptions(2)),
                 torch::nn::Conv2d(torch::nn::Conv2dOptions(32, 64, 3)),
                 torch::nn::ReLU(torch::nn::ReLUOptions()),
                 torch::nn::MaxPool2d(torch::nn::MaxPool2dOptions(2)),
                 torch::nn::Conv2d(torch::nn::Conv2dOptions(64, 64, 3)),
                 torch::nn::ReLU(torch::nn::ReLUOptions()),
                 torch::nn::Flatten(torch::nn::FlattenOptions()),
                 torch::nn::Linear(torch::nn::LinearOptions(576, 64)),
                 torch::nn::ReLU(torch::nn::ReLU()),
                 torch::nn::Linear(torch::nn::LinearOptions(64, 10)),
                 torch::nn::LogSoftmax(torch::nn::LogSoftmaxOptions(1))) {
     network->train(false);
     data.reset(new torch::data::datasets::MNIST(DATA_PATH.toStdString(), torch::data::datasets::MNIST::Mode::kTest));
     current_index = 0;
     sendImage();
 }
References current_index, data, DATA_PATH, network, and sendImage().
Member Function Documentation
changeImage
void Network::changeImage (int increment) slot
The slot that records when a new image should be predicted and displayed.
This will update all the internal indices and ultimate result in a new example signal to be emitted. If the end of the dataset has been reached, it will wrap around to the start. Likewise for traveling backwards.
Parameters
increment The number of places to offset when selecting the new image. For instance, a value of 1 will change the image from index N to index N+1. If zero is sent, a new prediction is still made and an image emitted.
Definition at line 33 of file network.cpp.
{
     // To avoid overflow, this uses a series of while loops to bring the
     // requested increment into the range of data values. The assumption
     // is that the data size won't approach the max value of int.
     // There are probably ways to do this better, but I was having
     // difficulty with handling negative increments.
     size_t data_size = data->size().value();
     while (increment < 0) {
         increment += data_size;
     }
     while (increment >= data_size) {
         increment -= data_size;
     }
     current_index += increment;
     while (current_index >= data_size) {
         current_index -= data_size;
     }
     sendImage();
 }
References current_index, data, and sendImage().
Referenced by TestNetwork::cycleImage(), and main().
convertToImage()
QImage Network::convertToImage (torch::Tensor tensor) private
Takes a Tensor and converts it into a QImage.
This currently assumes this will be a 28x28 pixel image. It flattens the tensor and then fills in the QImage.
Parameters
tensor The input tensor, assumed to have the dimensions of 28x28.
Returns
The resulting image. It is 28x28 and 8-bit grayscale. The image is copied from the tensor, so there is no issue with implicit sharing.
Definition at line 92 of file network.cpp.
{
     torch::Tensor flat_tensor = tensor.flatten();
     float * raw_data = flat_tensor.data<float>();
     int64_t pixel_count = flat_tensor.size(0);
     uchar * pixel_values = new uchar[pixel_count];
     for (int i = 0; i < pixel_count; ++i) {
         float pixel_float_value = raw_data[i] * 255.0;
         uchar pixel_value = static_cast<uchar>(qRound(pixel_float_value));
         pixel_value = qBound(uchar(0), pixel_value, uchar(255));
         // Invert the color.
         pixel_values[i] = 255 - pixel_value;
     }
     QImage image(pixel_values, 28, 28, QImage::Format_Grayscale8);
     return image.copy();
 }
Referenced by sendImage().
example
void Network::example (int index, QImage image, int truth, int prediction) signal
A signal containing a new example and associated labels.
Parameters
index The index number where this example can be found in the dataset.
image The image itself.
truth The actual label from the dataset.
prediction The predicted label from network.
Referenced by main(), and sendImage().
sendImage()
void Network::sendImage () private
The method to predict the image and output a example signal.
This loads the image at index value current_index, then uses network to make a prediction about the data. It also calls convertToImage to create a QImage. All this information is then sent out on the signal.
Definition at line 108 of file network.cpp.
{
     // Get whichever iteration is requested.
     torch::data::Example<torch::Tensor, torch::Tensor> current_example = data->get(current_index);
     // The inputs to the network have to be of the shape {batch_size, channels, width, height}
     // so add an additional dimension into the tensor.
     torch::Tensor input = current_example.data.unsqueeze(0);
     torch::Tensor prediction_distribution = network->forward(input);
     // Whichever index has the max value is the predicted value.
     int prediction = prediction_distribution.argmax(1).item<int>();
     QImage image = convertToImage(current_example.data);
     int label = current_example.target.item<int>();
     emit example(current_index, image, label, prediction);
 }
References convertToImage(), current_index, data, example(), and network.
Referenced by changeImage(), and Network().
startTraining
void Network::startTraining (unsigned int batch_size, unsigned int epochs) slot
The slot that requests to train the network on training data.
This will cause the network to run some training. It will create a DataLoader for the dataset, establish optimization and loss functions, then run for the requested number of epochs. During this time, progress will be output using the trainingUpdate signal. Completion will also be signalled using the same means.
Parameters
batch_size How many datapoints to include in each iteration. If this is larger than the dataset, it is assumed to be the dataset.
epochs The number of epochs to run for.
Definition at line 53 of file network.cpp.
{
     // No need to do anything if either value is zero.
     if (batch_size == 0 || epochs == 0) {
         emit trainingUpdate(1, 1, epochs, epochs, 0.0);
         return;
     }
     network->train(true);
     // This will be a little hacky in that it opens up the dataset seperate from
     // the one done at object instantiation. This is to swap the mode.
     auto train_data = torch::data::datasets::MNIST(DATA_PATH.toStdString(), torch::data::datasets::MNIST::Mode::kTrain).map(torch::data::transforms::Stack<>());
     // Estimate about how many batches will be run each epoch.
     uint batches = qCeil(train_data.size().value() / static_cast<double>(batch_size));
     torch::data::DataLoaderOptions options;
     options.batch_size(batch_size);
     options.workers(2);
     auto data_loader = torch::data::make_data_loader(std::move(train_data), options);
     // Create the optimizer functions
     torch::optim::RMSprop optimizer(network->parameters(), torch::optim::RMSpropOptions());
     // Do the training
     for (int64_t epoch = 1; epoch <= epochs; ++epoch) {
         torch::Tensor loss;
         uint batch_index = 1;
         for (torch::data::Example<> & batch : *data_loader) {
             network->zero_grad();
             torch::Tensor images = batch.data;
             torch::Tensor labels = batch.target;
             torch::Tensor predictions = network->forward(images);
             loss = torch::nll_loss(predictions, labels);
             loss.backward();
             optimizer.step();
             emit trainingUpdate(batch_index, batches, static_cast<uint>(epoch), epochs, loss.item<float>());
             // Process this update so the user actually sees progress.
             QCoreApplication::processEvents();
             batch_index++;
         }
     }
     network->train(false);
 }
References DATA_PATH, network, and trainingUpdate().
Referenced by main(), and TestNetwork::train().
trainingUpdate
void Network::trainingUpdate (unsigned int batch, unsigned int total_batches, unsigned int epoch, unsigned int total_epochs, float latest_loss) signal
A signal that periodically emits to showcase training progress.
Training is signalled to be complete when epoch == total_epochs.
Parameters
batch The batch number that just completed.
total_batches The approximate total batches that will be run each epoch.
epoch The epoch number that just completed.
total_epochs The total number of epochs to trair for.
latest_loss The loss value calculated for the just completed epoch.
Referenced by main(), and startTraining().
Member Data Documentation
current_index
size_t Network::current_index private
The index of the current image that should be displayed.
Definition at line 100 of file network.h.
Referenced by changeImage(), Network(), and sendImage().
data
QScopedPointer<torch::data::datasets::MNIST> Network::data private
A pointer to the loaded dataset.
Definition at line 104 of file network.h.
Referenced by changeImage(), Network(), and sendImage().
DATA_PATH
const QString Network::DATA_PATH = "C:/Users/kylem/Documents/dev/src/mnist-viewer/data" private
The hard coded location of the dataset file.
Definition at line 108 of file network.h.
Referenced by Network(), and startTraining().
network
torch::nn::Sequential Network::network private
The MNIST network that does the prediction.
Definition at line 112 of file network.h.
Referenced by Network(), sendImage(), and startTraining().
The documentation for this class was generated from the following files:
include/network.h
src/network.cpp